### ISSUE TITLE
[PE-D][Tester E] Bug: `select` command missing from the UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W17-1/tp#117]
Multiple commands are missing from the UG.

For example, the `select` command does not appear in the UG at all, so users are unable to know it exists to see the events in their trips.

-------------
Labels: `severity.High` `type.DocumentationBug`
original: seelengxd/ped#2

**Comment by seanmanik** [comment]
This UG bug has been fixed.
