### ISSUE TITLE
[PE-D][Tester C] User Guide does not specify that users cannot have duplicate events and trips

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W17-1/tp#119]
A minor feature which was not documented, but perhaps it might help users be more aware that the Travelr application requires there to be no duplicate events and trips (in terms of names).

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: lfrostbytee/ped#1

**Comment by seanmanik** [comment]
This UG bug has been fixed.
