### ISSUE TITLE
[PE-D][Tester D] Overzealous input handling 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W17-1/tp#132]
![image.png](https://raw.githubusercontent.com/seanflyyy/ped/main/files/1b313cb6-0222-49bd-aa2f-d5709169c727.png)

Here, I tried to add the event to the trip but I got an error, maybe you should make it such that it is case insensitive.

It can be quite irritating to the user.

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: seanflyyy/ped#5

**Comment by seanmanik** [comment]
Explanation added.
