### ISSUE TITLE
[PE-D][Tester A] Duplicated UG title

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W17-1/tp#146]
![image.png](https://raw.githubusercontent.com/jhchee18/ped/main/files/23ffe1b6-9efc-47cb-9769-92df4c315ca1.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: jhchee18/ped#12

**Comment by seanmanik** [comment]
This UG bug has been fixed.
