### ISSUE TITLE
[PE-D][Tester D] overall case insensitivity

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W17-1/tp#147]
I think that in general the commands should be case insensitive so if you have a trip that is Solo Trip and I want to let's say assign an event, it should be able to understand that solo trip === Solo Trip, otherwise it can be rather troublesome to assign an event to a trip

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: seanflyyy/ped#10

**Comment by seanmanik** [comment]
Justify case sensitivity

**Comment by seanmanik** [comment]
Justified
