### ISSUE TITLE
[PE-D][Tester A] Wrong command result

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W17-1/tp#158]
input: `mark 10`

output: does not display all trips and all events in bucket list, instead it closes the summary window.

![image.png](https://raw.githubusercontent.com/jhchee18/ped/main/files/47f91ca0-0dbc-4123-8c6c-d284b28ee398.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: jhchee18/ped#15

**Comment by seanmanik** [comment]
This bug has been fixed.
