### ISSUE TITLE
[PE-D][Tester E] Bug: `list-e` is not accurate in UG.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W17-1/tp#162]
`list-e` claims to `Shows a list of all events added.` but only `view` does that. `list-e` only shows events in the bucket list.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: seelengxd/ped#8

**Comment by seanmanik** [comment]
This UG bug has been fixed.
