### ISSUE TITLE
[PE-D][Tester A] Storage file name does not make sense

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W17-1/tp#163]
`addressbook.json` does not make any sense in Travelr App

![image.png](https://raw.githubusercontent.com/jhchee18/ped/main/files/54f607dd-6512-4d85-bfbd-33d98e772b9e.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: jhchee18/ped#17

**Comment by seanmanik** [comment]
This bug has been fixed.
